export const HTML = "http://www.w3.org/1999/xhtml"
export const XML = "http://www.w3.org/XML/1998/namespace"
export const XMLNS = "http://www.w3.org/2000/xmlns/"
export const MathML = "http://www.w3.org/1998/Math/MathML"
export const SVG = "http://www.w3.org/2000/svg"
export const XLink = "http://www.w3.org/1999/xlink"
